# Generated by Django 3.0.7 on 2020-06-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CotDate',
            new_name='CotData',
        ),
    ]
