# Generated by Django 3.0.7 on 2020-06-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200604_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotdata',
            options={'verbose_name': 'cot data', 'verbose_name_plural': 'cot data'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'currency', 'verbose_name_plural': 'currencies'},
        ),
        migrations.AddField(
            model_name='cotdata',
            name='long_change',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotdata',
            name='long_percent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotdata',
            name='short_change',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotdata',
            name='short_percent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
